// Run after changing anything in app/:  node tools/build.mjs
//  1. renders PNG app icons from the SVG icon (needs Playwright + Chromium)
//  2. writes app/precache.js: every file the service worker caches for offline play,
//     plus a version hash so phones pick up updates.
import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const APP = new URL('../app/', import.meta.url).pathname;

if (!process.argv.includes('--no-icons')) {
  const { chromium } = await import('playwright');
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const shots = [
    ['assets/brand/app-icon-1024.svg', 'icons/icon-192.png', 192, 0],
    ['assets/brand/app-icon-1024.svg', 'icons/icon-512.png', 512, 0],
    ['assets/brand/app-icon-1024-square.svg', 'icons/maskable-512.png', 512, 0],
    ['assets/brand/app-icon-1024-square.svg', 'icons/apple-touch-icon.png', 180, 0]
  ];
  for (const [src, out, size] of shots) {
    const svg = readFileSync(join(APP, src), 'utf8');
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(`<body style="margin:0;background:transparent"><img style="width:${size}px;height:${size}px;display:block" src="data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}">`);
    await page.waitForTimeout(100);
    await page.screenshot({ path: join(APP, out), omitBackground: true });
  }
  await browser.close();
  console.log('icons rendered');
}

const files = [];
const walk = dir => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (f.startsWith('.') || f.startsWith('_')) continue;
    if (statSync(p).isDirectory()) walk(p);
    else files.push(relative(APP, p));
  }
};
walk(APP);
const list = files.filter(f => !['sw.js', 'precache.js'].includes(f)).sort();
const hash = createHash('sha1');
for (const f of list) hash.update(f).update(readFileSync(join(APP, f)));
const version = hash.digest('hex').slice(0, 10);
writeFileSync(join(APP, 'precache.js'), `// Generated by tools/build.mjs. Do not edit.\nself.PRECACHE_VERSION = '${version}';\nself.PRECACHE = ${JSON.stringify(['./', ...list], null, 1)};\n`);
console.log(`precache: ${list.length} files, version ${version}`);
